apiVersion: v1
kind: Secret
metadata:
  name: llama-inference-secret
type: Opaque
data:
  AWS_ACCESS_KEY_ID: "QUtJQVhXSERMUzVDWkIyNVdKN0o=" 
  AWS_SECRET_ACCESS_KEY: "V0crRUpNaFQ0MnNnYTZxN3hBWWdFSTRwRXYyd2ZhVnJhYURLKzZROQ=="
  AWS_DEFAULT_REGION: "ZXUtY2VudHJhbC0x"    
